### PR TITLE
[superstruct] Add note about type-inference

### PR DESCRIPTION
**Pull request by benbender**
Add note about type-inference with typescript and superstruct

### CODE REVIEW

**Comment by pablo-abc** [comment]
This is a nice detail to add, thanks! If you have the time, would you mind adding a section for this on `reporter-yup` and `reporter-zod`? I understand both of them offer similar utilities. I'll need to add this to the site afterwards.

**Comment by benbender** [comment]
Wouldn't be a problem for Zod as I know that it works. For Yup I would have to look it up and test it, as I never used it.

**Comment by benbender** [comment]
@pablo-abc Updated the pr for the remaining two validators and updated the example to use the named export which was introduced with zod3. Should be ready now.

**Review by pablo-abc — APPROVED** [review]
Looks perfect now! Thanks a lot!

**Pull request merged**
