### PR TITLE
Allow defining CSS classes for dynamic created elements

### PR DESCRIPTION
**Pull request by hmaesta**
As a [Tailwind CSS](https://tailwindcss.com/) user I always try to declare classes to an element using `class=""` instead of doing by by `<style>` tag. That's important to keep our final bundled CSS file as little as it can be.

Using Felte with `@felte/reporter-dom` I can't declare the classes of the `<span>` created inside the main `<div>`. The only option, [as described in README](https://github.com/pablo-abc/felte/blob/main/packages/reporter-dom/README.md#styling), is using the CSS selector `[data-felte-reporter-dom-single-message]`.

This PR creates the `singleAttributes` and `listAttributes` params that can be used to attach classes to dynamic created elements.

### How to use
```js
extend: [
   reporter({
      single: true,
      singleAttributes: {
         class: ['bg-red-600', 'text-white', 'inline-block', 'py-1', 'px-2', 'rounded'],
      },
      // or, if using `single: false` 
      listAttributes: {
         class: ['list-none', 'bg-red-600', 'text-white', 'block', 'rounded'], // will be applied to main element (`ul` or `ol`)
         itemClass: ['block', 'py-1', 'px-2'], // will be applied to child element (`li`)
      }
   })
],
```

### DOM
```html
<div id="name-validation" data-felte-reporter-dom-for="name">
   <span 
       class="bg-red-600 text-white inline-block py-1 px-2 rounded"
       aria-live="polite"
       data-felte-reporter-dom-single-message=""
   >
      Required field
   </span>
</div>
```

### CODE REVIEW

**Comment by pablo-abc** [comment]
Sorry for the delay, @hmaesta . This looks really good! I'll pull this and try this on my local machine some time tomorrow.

Just a minor detail, since each list item is also a separate element, maybe having a `listItemAttributes` object in the root would be more intuitive than having an `itemClass` inside of `listAttributes`? For the sake of it likely needing to be more extensible in the future. But that's the only thing! Once it's merged I'll add tests for this.

**Comment by hmaesta** [comment]
> maybe having a `listItemAttributes` object in the root would be more intuitive than having an `itemClass` inside of `listAttributes`? 

Just pushed this changes, Pablo. Thank you for your patience.

**Review by pablo-abc — APPROVED** [review]
Looks perfect now! I'll add tests to this and then publish it. Thank you so much for your contribution!

Would you like to be added as a contributors? This repo is following the [all contributors](https://allcontributors.org) spec, and your contribution is definitely helpful to Felte.

**Comment by pablo-abc** [comment]
Sorry for the delay, @hmaesta. When adding tests I noticed some minor issues that have been fixed. Your PR has been published in @felte/reporter-dom@0.2.1 (published is a patch. Since we're still pre-1.0.0 I'm reserving "minor" versions for breaking changes).

**Pull request merged**
